INSERT INTO card_types (type_name) VALUES
('Grass'),
('Fire'),
('Water'),
('Lightning'),
('Psychic'),
('Fighting'),
('Darkness'),
('Metal'),
('Fairy'),
('Dragon'),
('Colorless'),
('Trainer'),
('Energy');

INSERT INTO card_stages (stage_name) VALUES
('Basic'),
('Stage 1'),
('Stage 2'),
('V'),
('VMAX'),
('EX'),
('Mega EX'),
('GX'),
('VSTAR'),
('Restored');

INSERT INTO collection_sets (set_name, release_date, total_cards) VALUES
('Base Set', '1999-01-09', 102),
('Jungle', '1999-06-16', 64),
('Fossil', '1999-10-10', 62),
('Sword & Shield: Rebel Clash', '2020-05-01', 192),
('Scarlet & Violet: Paldea Evolved', '2023-06-09', 279);

INSERT INTO tcg_cards (
    name, hp, card_type_id, stage_id, illustrator, card_number, 
    attacks, weakness, resistance, retreat_cost, special_rule, collection_set_id
) VALUES
('Pidgeot', 90, 11, 3, 'Ken Sugimori', '8/102', 'Hurricane: Flip a coin. If tails, this attack does nothing. (40 Damage)', 'Lightning (x2)', 'Fighting (-30)', 0, 'Evolves from Pidgeotto.', 1),
('Gyarados', 100, 3, 2, 'Mitsuhiro Arita', '6/102', 'Dragon Rage: Flip a coin. If tails, this attack does 50 damage to Gyarados. (100 Damage)', 'Lightning (x2)', 'Fighting (-30)', 3, 'Evolves from Magikarp.', 1),
('Clefairy', 40, 11, 1, 'Ken Sugimori', '5/102', 'Sing: The Defending Pokémon is now Asleep. (0 Damage)', 'Fighting (x2)', NULL, 1, NULL, 1),
('Ninetales', 80, 2, 2, 'Ken Sugimori', '12/102', 'Lure: Switch 1 of your opponent''s Benched Pokémon with the Defending Pokémon. (0 Damage)', 'Water (x2)', NULL, 1, 'Evolves from Vulpix.', 1),
('Arcanine', 90, 2, 2, 'Ken Sugimori', '23/102', 'Fire Blast: Discard 1 Fire Energy attached to Arcanine. (50 Damage)', 'Water (x2)', NULL, 2, 'Evolves from Growlithe.', 1),
('Jynx', 70, 5, 1, 'Ken Sugimori', '31/102', 'Energy Freeze: Flip a coin. If heads, the Defending Pokémon is now Paralyzed. (0 Damage)', 'Psychic (x2)', NULL, 2, NULL, 1),
('Mewtwo', 60, 5, 1, 'Ken Sugimori', '10/102', 'Psychic: This attack does 10 damage plus 10 more damage for each Energy attached to the Defending Pokémon. (10+ Damage)', 'Psychic (x2)', NULL, 3, NULL, 1),
('Muk', 70, 5, 2, 'Ken Sugimori', '13/102', 'Sludge: Flip a coin. If heads, the Defending Pokémon is now Poisoned. (30 Damage)', 'Psychic (x2)', NULL, 2, 'Evolves from Grimer.', 1),
('Gloom', 60, 1, 2, 'Ken Sugimori', '37/64', 'PoisonPowder: The Defending Pokémon is now Poisoned. (20 Damage)', 'Fire (x2)', NULL, 1, 'Evolves from Oddish. Jungle Set.', 2),
('Parasect', 60, 1, 2, 'Ken Sugimori', '39/64', 'Spore: The Defending Pokémon is now Asleep. (20 Damage)', 'Fire (x2)', NULL, 1, 'Evolves from Paras. Jungle Set.', 2),
('Clefable', 70, 11, 2, 'Ken Sugimori', '1/64', 'Metronome: Choose 1 of the Defending Pokémon''s attacks. Metronome copies that attack. (0 Damage)', 'Fighting (x2)', NULL, 2, 'Evolves from Clefairy. Jungle Set.', 2),
('Wigglytuff', 90, 11, 2, 'Ken Sugimori', '16/64', 'Do the Wave: Does 10 damage times the number of Pokémon on your Bench. (10x Damage)', 'Fighting (x2)', NULL, 2, 'Evolves from Jigglypuff. Jungle Set.', 2),
('Tauros', 60, 11, 1, 'Ken Sugimori', '47/64', 'Stomp: Flip a coin. If heads, this attack does 20 more damage. (10+ Damage)', 'Fighting (x2)', NULL, 1, NULL, 2),
('Rhydon', 100, 6, 2, 'Ken Sugimori', '45/64', 'Horn Drill: Flip a coin. If tails, this attack does nothing. (50 Damage)', 'Grass (x2)', 'Lightning (-30)', 3, 'Evolves from Rhyhorn. Jungle Set.', 2),
('Poliwrath', 90, 3, 3, 'Ken Sugimori', '13/64', 'Whirlpool: If the Defending Pokémon has any Energy cards attached to it, choose 1 of them and discard it. (40 Damage)', 'Grass (x2)', NULL, 3, 'Evolves from Poliwhirl. Jungle Set.', 2),
('Slowbro', 60, 5, 2, 'Ken Sugimori', '38/64', 'Disable: Choose 1 of the Defending Pokémon''s attacks. That Pokémon can''t use that attack during your opponent''s next turn. (20 Damage)', 'Psychic (x2)', NULL, 1, 'Evolves from Slowpoke. Fossil Set.', 3),
('Hypno', 90, 5, 2, 'Ken Sugimori', '23/62', 'Darkness Revealed: Flip a coin. If heads, the Defending Pokémon is now Asleep. (30 Damage)', 'Psychic (x2)', NULL, 2, 'Evolves from Drowzee. Fossil Set.', 3),
('Hitmonlee', 60, 6, 1, 'Ken Sugimori', '7/62', 'High Jump Kick (40)', 'Psychic (x2)', NULL, 1, NULL, 3),
('Weezing', 60, 5, 2, 'Ken Sugimori', '48/62', 'Smokescreen: If the Defending Pokémon tries to attack during your opponent''s next turn, your opponent flips a coin. If tails, that attack does nothing. (20 Damage)', 'Psychic (x2)', NULL, 1, 'Evolves from Koffing. Fossil Set.', 3),
('Kingler', 70, 3, 2, 'Ken Sugimori', '38/62', 'Shell Attack (30)', 'Lightning (x2)', NULL, 2, 'Evolves from Krabby. Fossil Set.', 3),
('Zamazenta V', 220, 8, 4, '5ban Graphics', '139/192', 'Brave Shield: During your opponent''s next turn, prevent all damage done to this Pokémon by attacks from Pokémon VMAX. (130 Damage)', 'Fire (x2)', 'Grass (-30)', 2, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Boltund V', 200, 4, 4, '5ban Graphics', '67/192', 'Electrify: Attach up to 2 Lightning Energy cards from your hand to your Pokémon in any way you like. (0 Damage)', 'Fighting (x2)', NULL, 1, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Coalossal V', 220, 6, 4, '5ban Graphics', '106/192', 'Crushing Press: Discard an Energy from your opponent''s Active Pokémon. (130 Damage)', 'Grass (x2)', NULL, 4, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Mew V', 180, 5, 4, '5ban Graphics', '69/192', 'Energy Mix: Search your deck for a basic Energy card and attach it to this Pokémon. Then, shuffle your deck. (0 Damage)', 'Darkness (x2)', 'Fighting (-30)', 1, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Rotom V', 190, 4, 4, '5ban Graphics', '73/192', 'Instant Charge: If this Pokémon is in the Active Spot, you may use this Ability once during your first turn. Draw 3 cards. (0 Damage)', 'Fighting (x2)', NULL, 1, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Galarian Perrserker V', 210, 8, 4, '5ban Graphics', '118/192', 'Steel Blade: This attack does 100 more damage if you played a Supporter card from your hand this turn. (100+ Damage)', 'Fire (x2)', 'Grass (-30)', 2, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Full Face Guard', NULL, 12, 1, 'Ryo Ueda', '156/192', NULL, NULL, NULL, NULL, 'The Pokémon this card is attached to has no Weakness. Rebel Clash.', 4),
('Miriadon ex', 220, 4, 1, '5ban Graphics', '81/279', 'Photon Blaster: During your next turn, this Pokémon can''t use Photon Blaster. (220 Damage)', 'Fighting (x2)', NULL, 2, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5),
('Spidops ex', 260, 1, 2, '5ban Graphics', '13/279', 'Filament Trap: Flip a coin. If heads, the Defending Pokémon is now Paralyzed. (180 Damage)', 'Fire (x2)', NULL, 2, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5),
('Slowking ex', 270, 5, 2, '5ban Graphics', '104/279', 'Memory Skip: Choose 1 of the Defending Pokémon''s attacks. That Pokémon can''t use that attack during your opponent''s next turn. (160 Damage)', 'Darkness (x2)', 'Fighting (-30)', 3, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5),
('Garganacl ex', 270, 6, 2, '5ban Graphics', '156/279', 'Rock Cannon: This attack does 80 damage to 1 of your opponent''s Benched Pokémon. (180 Damage)', 'Grass (x2)', NULL, 4, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5),
('Baxcalibur', 160, 3, 3, 'Ken Sugimori', '60/279', 'Absolute Zero: This attack does 100 damage to 1 of your opponent''s Benched Pokémon. (180 Damage)', 'Metal (x2)', NULL, 2, 'Evolves from Arctibax. Paldea Evolved.', 5),
('Super Rod', NULL, 12, 1, 'Studio Bora Inc.', '188/279', NULL, NULL, NULL, NULL, 'Shuffle up to 3 in any combination of Pokémon and basic Energy cards from your discard pile into your deck. Paldea Evolved.', 5),
('Buddy-Buddy Poffin', NULL, 12, 1, 'Ryo Ueda', '194/279', NULL, NULL, NULL, NULL, 'Search your deck for up to 2 Basic Pokémon with 70 HP or less and put them onto your Bench.', 5),
('Rillaboom V', 220, 1, 4, '5ban Graphics', '15/192', 'Drum Beat: (180 Damage)', 'Fire (x2)', NULL, 3, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Indeedee V', 180, 5, 4, '5ban Graphics', '90/192', 'Psychic: This attack does 10 damage plus 30 more damage for each Energy attached to the Defending Pokémon. (10+ Damage)', 'Darkness (x2)', 'Fighting (-30)', 1, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Eiscue V', 190, 3, 4, '5ban Graphics', '40/192', 'Headbutt: (50 Damage)', 'Metal (x2)', NULL, 2, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Centiskorch V', 210, 2, 4, '5ban Graphics', '33/192', 'Sizzling Spit: This attack does 40 damage to 1 of your opponent''s Benched Pokémon. (60 Damage)', 'Water (x2)', NULL, 2, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Coalossal VMAX', 330, 6, 5, '5ban Graphics', '107/192', 'G-Max Boulder: This attack does 200 damage to 1 of your opponent''s Benched Pokémon. (100 Damage)', 'Grass (x2)', NULL, 4, 'VMAX Rule: When your Pokémon VMAX is Knocked Out, your opponent takes 3 Prize Cards. Rebel Clash.', 4),
('Morpeko V', 170, 4, 4, '5ban Graphics', '79/192', 'Sparking Tackle: This attack does 20 damage times the amount of Energy attached to this Pokémon. (20x Damage)', 'Fighting (x2)', NULL, 1, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Carkol', 90, 6, 2, 'Sekio', '105/192', 'Ram: (60 Damage)', 'Grass (x2)', NULL, 3, 'Evolves from Rolycoly. Rebel Clash.', 4),
('Orbeetle V', 180, 1, 4, '5ban Graphics', '20/192', 'Strafe: Switch this Pokémon with 1 of your Benched Pokémon. (30 Damage)', 'Fire (x2)', NULL, 1, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Eiscue', 120, 3, 1, 'Sanosuke Sakuma', '41/192', 'Headbutt (20)', 'Metal (x2)', NULL, 2, NULL, 4),
('Galar Mine', NULL, 12, 1, 'Oswaldo Kuno', '160/192', NULL, NULL, NULL, NULL, 'The Retreat Cost of all Basic Pokémon (both yours and your opponent''s) is 1 more. Rebel Clash.', 4),
('Arctibax', 100, 3, 2, 'Saya Nanbu', '59/279', 'Tackle (40)', 'Metal (x2)', NULL, 2, 'Evolves from Frigibax. Paldea Evolved.', 5),
('Frigibax', 70, 3, 1, 'Shibuzoh.', '58/279', 'Icy Wind (20)', 'Metal (x2)', NULL, 1, NULL, 5),
('Fidough', 50, 11, 1, 'Misa Tsutsui', '168/279', 'Lick (10)', 'Fighting (x2)', NULL, 1, NULL, 5),
('Palafin', 140, 3, 2, 'Saya Nanbu', '53/279', 'Justice Kick: If this Pokémon moved from the Bench to the Active Spot this turn, this attack does 210 damage. (30+ Damage)', 'Lightning (x2)', NULL, 2, 'Evolves from Finizen. Paldea Evolved.', 5),
('Pachirisu', 70, 4, 1, 'Shibuzoh.', '82/279', 'Thunder Shock: Flip a coin. If heads, the Defending Pokémon is now Paralyzed. (10 Damage)', 'Fighting (x2)', NULL, 1, NULL, 5),
('Great Tusk ex', 240, 6, 1, '5ban Graphics', '120/279', 'Giant Tusk: Discard the top 3 cards of your opponent''s deck. (120 Damage)', 'Psychic (x2)', NULL, 4, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5);
INSERT INTO tcg_cards (
    name, hp, card_type_id, stage_id, illustrator, card_number, 
    attacks, weakness, resistance, retreat_cost, special_rule, collection_set_id
) VALUES
('Venusaur', 100, 1, 3, 'Mitsuhiro Arita', '15/102', 'Solarbeam (60)', 'Fire (x2)', NULL, 2, 'Evolves from Ivysaur. Base Set.', 1),
('Vulpix', 50, 2, 1, 'Ken Sugimori', '68/102', 'Confuse Ray: Flip a coin. If heads, the Defending Pokémon is now Confused. (0 Damage)', 'Water (x2)', NULL, 1, NULL, 1),
('Growlithe', 60, 2, 1, 'Ken Sugimori', '28/102', 'Bite (10)', 'Water (x2)', NULL, 1, NULL, 1),
('Abra', 30, 5, 1, 'Ken Sugimori', '43/102', 'Psyshock (10)', 'Psychic (x2)', NULL, 1, NULL, 1),
('Kadabra', 60, 5, 2, 'Ken Sugimori', '32/102', 'Super Psy: Does 20 damage plus 10 more damage for each Energy attached to Kadabra but not used to pay for this attack''s Energy cost. (20+ Damage)', 'Psychic (x2)', NULL, 2, 'Evolves from Abra. Base Set.', 1),
('Alakazam', 80, 5, 3, 'Ken Sugimori', '1/102', 'Damage Swap: As often as you like during your turn, move 1 damage counter from 1 of your Pokémon to another of your Pokémon. (0 Damage)', 'Psychic (x2)', NULL, 3, 'Evolves from Kadabra. Base Set.', 1),
('Onix', 90, 6, 1, 'Ken Sugimori', '56/102', 'Rock Throw (10)', 'Grass (x2)', 'Lightning (-30)', 3, NULL, 1),
('Zubat', 40, 11, 1, 'Ken Sugimori', '70/102', 'Leech Life: Remove 1 damage counter from Zubat. (10 Damage)', 'Lightning (x2)', 'Fighting (-30)', 1, NULL, 1),
('Grimer', 50, 5, 1, 'Ken Sugimori', '38/102', 'Poison Gas: Flip a coin. If heads, the Defending Pokémon is now Poisoned. (0 Damage)', 'Psychic (x2)', NULL, 1, NULL, 1),
('Rattata', 30, 11, 1, 'Ken Sugimori', '61/102', 'Super Fang: Flip a coin. If heads, the Defending Pokémon is Knocked Out. (0 Damage)', 'Fighting (x2)', NULL, 1, NULL, 1),
('Raticate', 60, 11, 2, 'Ken Sugimori', '40/102', 'Bite (20)', 'Fighting (x2)', NULL, 1, 'Evolves from Rattata. Base Set.', 1),
('Doduo', 50, 11, 1, 'Ken Sugimori', '48/102', 'Focus Energy: During your next turn, Doduo''s Peck attack does 30 more damage. (0 Damage)', 'Lightning (x2)', 'Fighting (-30)', 1, NULL, 1),
('Dodrio', 70, 11, 2, 'Ken Sugimori', '11/64', 'Tri Attack: Flip 3 coins. This attack does 30 damage times the number of heads. (30x Damage)', 'Lightning (x2)', 'Fighting (-30)', 1, 'Evolves from Doduo. Jungle Set.', 2),
('Vileplume GX', 230, 1, 3, '5ban Graphics', '4/192', 'Faint Attack: This attack does 50 damage to 1 of your opponent''s Benched Pokémon. (50 Damage)', 'Fire (x2)', NULL, 2, 'GX Rule: When your Pokémon GX is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Cramorant V', 190, 3, 4, '5ban Graphics', '39/192', 'Spit Shot: This attack does 160 damage to 1 of your opponent''s Benched Pokémon. (0 Damage)', 'Lightning (x2)', NULL, 1, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Boltund VMAX', 320, 4, 5, '5ban Graphics', '68/192', 'Max Lightning: This attack does 10 more damage for each Energy attached to your opponent''s Active Pokémon. (120+ Damage)', 'Fighting (x2)', NULL, 1, 'VMAX Rule: When your Pokémon VMAX is Knocked Out, your opponent takes 3 Prize Cards. Rebel Clash.', 4),
('Iron Treads ex', 220, 8, 1, '5ban Graphics', '119/279', 'Hard Press: This attack does 30 more damage for each of your Benched Pokémon that has any damage counters on it. (60+ Damage)', 'Fire (x2)', 'Grass (-30)', 2, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5),
('Florges ex', 250, 11, 2, '5ban Graphics', '109/279', 'Pleasant Aroma: Heal 30 damage from all of your Pokémon. (100 Damage)', 'Metal (x2)', NULL, 2, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5),
('Gligar', 60, 6, 1, 'Ken Sugimori', '43/62', 'Poison Sting: Flip a coin. If heads, the Defending Pokémon is now Poisoned. (10 Damage)', 'Grass (x2)', 'Lightning (-30)', 1, NULL, 3),
('Seel', 60, 3, 1, 'Ken Sugimori', '41/102', 'Headbutt (10)', 'Lightning (x2)', NULL, 1, NULL, 1);
INSERT INTO tcg_cards (
    name, hp, card_type_id, stage_id, illustrator, card_number, 
    attacks, weakness, resistance, retreat_cost, special_rule, collection_set_id
) VALUES
('Porygon', 60, 11, 1, 'Ken Sugimori', '39/102', 'Convert: Flip a coin. If heads, change the Defending Pokémon''s Weakness type to a type of your choice. (0 Damage)', 'Fighting (x2)', NULL, 1, NULL, 1),
('Snorlax', 90, 11, 1, 'Ken Sugimori', '27/102', 'Body Slam: Flip a coin. If heads, the Defending Pokémon is now Paralyzed. (30 Damage)', 'Fighting (x2)', NULL, 3, 'Doze: If Snorlax has no Energy attached to it, Snorlax is Asleep.', 1),
('Seadra', 60, 3, 2, 'Ken Sugimori', '42/62', 'Agility: Flip a coin. If heads, prevent all effects of attacks, including damage, done to Seadra during your opponent''s next turn. (20 Damage)', 'Lightning (x2)', NULL, 1, 'Evolves from Horsea. Fossil Set.', 3),
('Cloyster', 50, 3, 2, 'Ken Sugimori', '33/62', 'Clamp: Flip a coin. If heads, the Defending Pokémon is Paralyzed. Cloyster can''t attack next turn. (30 Damage)', 'Lightning (x2)', NULL, 2, 'Evolves from Shellder. Fossil Set.', 3),
('Shellder', 30, 3, 1, 'Ken Sugimori', '54/62', 'Withdraw: Flip a coin. If heads, prevent all damage done to Shellder during your opponent''s next turn. (0 Damage)', 'Lightning (x2)', NULL, 1, NULL, 3),
('Omanyte', 40, 3, 1, 'Ken Sugimori', '55/62', 'Water Gun: Does 10 damage plus 10 more damage for each Water Energy attached to Omanyte but not used to pay for this attack''s Energy cost. (10+ Damage)', 'Grass (x2)', NULL, 1, NULL, 3),
('Kabutops', 80, 6, 3, 'Ken Sugimori', '9/62', 'Slash (40)', 'Grass (x2)', NULL, 2, 'Evolves from Kabuto. Fossil Set.', 3),
('Kabuto', 30, 6, 1, 'Ken Sugimori', '50/62', 'Scratch (10)', 'Grass (x2)', NULL, 1, NULL, 3),
('Gyarados V', 220, 3, 4, '5ban Graphics', '40/192', 'Hyper Beam: Discard an Energy from your opponent''s Active Pokémon. (120 Damage)', 'Lightning (x2)', NULL, 3, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Milotic V', 210, 3, 4, '5ban Graphics', '41/192', 'Hypnotic Gaze: The Defending Pokémon is now Asleep. (0 Damage)', 'Lightning (x2)', NULL, 2, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Vikavolt V', 210, 4, 4, '5ban Graphics', '66/192', 'Paralyzing Bolt: If this Pokémon is in the Active Spot, your opponent''s Active Pokémon is now Paralyzed. (100 Damage)', 'Fighting (x2)', NULL, 3, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Electrode V', 190, 4, 4, '5ban Graphics', '67/192', 'Voltaic Blast: Discard all Energy from this Pokémon. (180 Damage)', 'Fighting (x2)', NULL, 1, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Grimmsnarl V', 210, 7, 4, '5ban Graphics', '114/192', 'Crushing Fang: Discard a Special Energy from your opponent''s Active Pokémon. (100 Damage)', 'Grass (x2)', NULL, 3, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Gyarados VMAX', 330, 3, 5, '5ban Graphics', '40/192', 'G-Max Burst: This attack does 10 more damage for each damage counter on your opponent''s Active Pokémon. (180+ Damage)', 'Lightning (x2)', NULL, 3, 'VMAX Rule: When your Pokémon VMAX is Knocked Out, your opponent takes 3 Prize Cards. Rebel Clash.', 4),
('Eiscue VMAX', 300, 3, 5, '5ban Graphics', '41/192', 'Max Freeze: Flip a coin. If heads, the Defending Pokémon is now Paralyzed. (180 Damage)', 'Metal (x2)', NULL, 2, 'VMAX Rule: When your Pokémon VMAX is Knocked Out, your opponent takes 3 Prize Cards. Rebel Clash.', 4),
('Hydreigon V', 210, 7, 4, '5ban Graphics', '110/192', 'Dark Blast: This attack does 80 damage plus 50 more damage for each Dark Energy attached to this Pokémon. (80+ Damage)', 'Grass (x2)', NULL, 2, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Inteleon VMAX', 320, 3, 5, '5ban Graphics', '49/192', 'G-Max Fuzz: This attack does 150 damage to 1 of your opponent''s Benched Pokémon. (100 Damage)', 'Lightning (x2)', NULL, 2, 'VMAX Rule: When your Pokémon VMAX is Knocked Out, your opponent takes 3 Prize Cards. Rebel Clash.', 4),
('Boltund V', 200, 4, 4, '5ban Graphics', '67/192', 'Sparking Tackle: This attack does 40 more damage if this Pokémon has a Tool attached to it. (80+ Damage)', 'Fighting (x2)', NULL, 1, 'V Rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize Cards. Rebel Clash.', 4),
('Orbeetle VMAX', 300, 1, 5, '5ban Graphics', '21/192', 'G-Max Buzz: This attack does 50 damage to 1 of your opponent''s Benched Pokémon. (120 Damage)', 'Fire (x2)', NULL, 1, 'VMAX Rule: When your Pokémon VMAX is Knocked Out, your opponent takes 3 Prize Cards. Rebel Clash.', 4),
('Barraskewda', 110, 3, 2, 'Hasuno', '50/192', 'Aqua Jet: This attack does 30 damage to 1 of your opponent''s Benched Pokémon. (80 Damage)', 'Lightning (x2)', NULL, 1, 'Evolves from Arrokuda. Rebel Clash.', 4),
('Scovillain ex', 250, 2, 2, '5ban Graphics', '28/279', 'Spicy Pepper: This attack does 50 more damage for each Fire Energy attached to this Pokémon. (100+ Damage)', 'Water (x2)', NULL, 3, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5),
('Chi-Yu ex', 190, 2, 1, '5ban Graphics', '40/279', 'Burning Terror: Discard a Fire Energy from this Pokémon. This attack does 100 damage to 1 of your opponent''s Benched Pokémon. (0 Damage)', 'Water (x2)', NULL, 1, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5),
('Groudon ex', 230, 6, 1, '5ban Graphics', '130/279', 'Volcanic Press: Discard a Fighting Energy from this Pokémon. (220 Damage)', 'Grass (x2)', NULL, 4, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5),
('Miraidon ex', 220, 4, 1, '5ban Graphics', '81/279', 'Tachyon Bits: Put 1 damage counter on each of your opponent''s Pokémon. (0 Damage)', 'Fighting (x2)', NULL, 2, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5),
('Koraidon ex', 230, 6, 1, '5ban Graphics', '124/279', 'Claw Slash (130)', 'Psychic (x2)', NULL, 2, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5),
('Tinkaton ex', 300, 11, 2, '5ban Graphics', '152/279', 'Big Hammer: This attack does 20 more damage for each card in your hand. (10+ Damage)', 'Fighting (x2)', NULL, 2, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5),
('Pawmot', 130, 4, 2, 'Atsuko Nishida', '85/279', 'Electro Ball (120)', 'Fighting (x2)', NULL, 1, 'Evolves from Pawmo. Paldea Evolved.', 5),
('Arcanine', 130, 2, 2, 'Kouki Saitou', '32/279', 'Raging Fire: This attack does 50 more damage for each Fire Energy attached to this Pokémon. (50+ Damage)', 'Water (x2)', NULL, 2, 'Evolves from Growlithe. Paldea Evolved.', 5),
('Poliwag', 60, 3, 1, 'Ken Sugimori', '59/102', 'Bubble: Flip a coin. If heads, the Defending Pokémon is now Paralyzed. (10 Damage)', 'Grass (x2)', NULL, 1, NULL, 1),
('Poliwhirl', 80, 3, 2, 'Ken Sugimori', '39/102', 'Double Slap: Flip 2 coins. This attack does 30 damage times the number of heads. (30x Damage)', 'Grass (x2)', NULL, 2, 'Evolves from Poliwag. Base Set.', 1),
('Mankey', 50, 6, 1, 'Ken Sugimori', '53/102', 'Scratch (10)', 'Psychic (x2)', NULL, 1, NULL, 1),
('Primeape', 80, 6, 2, 'Ken Sugimori', '43/102', 'Karate Chop: This attack does 50 damage minus 10 damage for each damage counter on Primeape. (50- Damage)', 'Psychic (x2)', NULL, 1, 'Evolves from Mankey. Base Set.', 1),
('Tentacool', 30, 3, 1, 'Ken Sugimori', '56/62', 'Poison Sting: Flip a coin. If heads, the Defending Pokémon is now Poisoned. (10 Damage)', 'Lightning (x2)', NULL, 1, NULL, 3),
('Tentacruel', 60, 3, 2, 'Ken Sugimori', '44/62', 'Jellyfish Sting: Flip a coin. If heads, the Defending Pokémon is Paralyzed. (20 Damage)', 'Lightning (x2)', NULL, 1, 'Evolves from Tentacool. Fossil Set.', 3),
('Seaking', 80, 3, 2, 'Ken Sugimori', '47/62', 'Horn Attack (30)', 'Lightning (x2)', NULL, 1, 'Evolves from Goldeen. Fossil Set.', 3),
('Goldeen', 40, 3, 1, 'Ken Sugimori', '45/62', 'Peck (10)', 'Lightning (x2)', NULL, 1, NULL, 3),
('Staryu', 40, 3, 1, 'Ken Sugimori', '65/102', 'Swift: This attack does 20 damage to each of your opponent''s Pokémon. (20 Damage)', 'Lightning (x2)', NULL, 1, NULL, 1),
('Starmie', 60, 3, 2, 'Ken Sugimori', '64/102', 'Hydro Pump: Discard 1 Energy attached to Starmie. (40 Damage)', 'Lightning (x2)', NULL, 1, 'Evolves from Staryu. Base Set.', 1),
('Riolu', 70, 6, 1, 'Shibuzoh.', '114/279', 'Low Kick (20)', 'Psychic (x2)', NULL, 1, NULL, 5),
('Lucario ex', 250, 6, 2, '5ban Graphics', '115/279', 'Aura Sphere: This attack does 80 damage to 1 of your opponent''s Benched Pokémon. (120 Damage)', 'Psychic (x2)', NULL, 2, 'Pokémon ex Rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize Cards. Paldea Evolved.', 5);
